#!/usr/bin/env bash
set -euo pipefail

echo "[clean] Removing local build and test artifacts..."
rm -rf .pytest_cache .ruff_cache .mypy_cache build dist htmlcov
rm -f .coverage coverage.xml

# Remove bytecode caches generated by local runs.
find . -type d -name "__pycache__" -prune -exec rm -rf {} +
find . -type f -name "*.pyc" -delete
find . -type f -name "*.pyo" -delete
find . -type d -name "*.egg-info" -prune -exec rm -rf {} +
find . -type d -name ".ipynb_checkpoints" -prune -exec rm -rf {} +

# Remove runtime artifacts while preserving directory anchors.
if [[ -d data ]]; then
  find data -mindepth 1 ! -name ".gitkeep" -exec rm -rf {} +
fi

if [[ -d logs ]]; then
  find logs -mindepth 1 ! -name ".gitkeep" -exec rm -rf {} +
fi

if [[ -d reports ]]; then
  find reports -mindepth 1 ! -name ".gitkeep" -exec rm -rf {} +
fi

echo "[clean] Done."
